name = "tokenizer-visualization"
compatibility_date = "2025-12-05"
pages_build_output_dir = "./dist"

[env.production]
vars = { }

[env.production.secrets]
GEMINI_API_KEY = "AIzaSyCvyaumwRcwMi41STDc3l5PgFumOam_kK0wrangler secret put GEMINI_API_KEY
"

[env.preview]
vars = { }

[env.preview.secrets]
GEMINI_API_KEY = ""
